
name: Check Vercel Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-deployment:
    name: Check Vercel Deployment Status
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

    steps:
      - name: 📥 Récupérer le dernier déploiement
        id: get_deployment
        run: |
          DEPLOYMENT=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" \
            "https://api.vercel.com/v6/deployments?projectId=$VERCEL_PROJECT_ID&limit=1")
          
          DEPLOYMENT_ID=$(echo "$DEPLOYMENT" | jq -r '.deployments[0].uid')

          echo "Dernier déploiement ID: $DEPLOYMENT_ID"
          echo "deployment_id=$DEPLOYMENT_ID" >> "$GITHUB_OUTPUT"

      - name: ⏳ Attendre que le déploiement soit prêt
        run: |
          DEPLOYMENT_ID=${{ steps.get_deployment.outputs.deployment_id }}

          if [ -z "$DEPLOYMENT_ID" ] || [ "$DEPLOYMENT_ID" == "null" ]; then
            echo "::error title=Erreur::Aucun ID de déploiement trouvé"
            exit 1
          fi

          echo "🔍 Vérification du statut du déploiement ID: $DEPLOYMENT_ID"

          for i in {1..30}; do
            RESPONSE=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" \
              "https://api.vercel.com/v13/deployments/$DEPLOYMENT_ID")

            STATUS=$(echo "$RESPONSE" | jq -r '.readyState')
            URL=$(echo "$RESPONSE" | jq -r '.url')
            DOMAIN=$(echo "$RESPONSE" | jq -r '.alias[0] // "non disponible"')

            echo "::notice title=Statut::$STATUS"
            echo "🔄 Statut actuel: $STATUS"

            if [ "$STATUS" = "READY" ]; then
              echo "✅ Déploiement terminé avec succès!"
              echo "🌐 Domaine : https://$DOMAIN"
              echo "::notice title=Déploiement terminé::Domaine: https://$DOMAIN"
              exit 0
            elif [ "$STATUS" = "ERROR" ]; then
              echo "::error title=Échec du déploiement::Le déploiement a échoué ❌"
              exit 1
            fi

            sleep 10
          done

          echo "::error title=Délai dépassé::Le déploiement n'est pas prêt après 5 minutes"
          exit 1

