

name: Check Vercel Deployment

on:
  push:
    branches: [main]

jobs:
  check-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest deployment
        id: get_deployment
        run: |
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            "https://api.vercel.com/v6/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}")

          DEPLOYMENT_ID=$(echo "$RESPONSE" | jq -r '.deployments[0].uid')

          echo "Latest deployment ID: $DEPLOYMENT_ID"
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV

      - name: Check deployment status
        run: |
          echo "Waiting for deployment ID: $DEPLOYMENT_ID..."

          for i in {1..30}; do
            STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
              https://api.vercel.com/v13/deployments/$DEPLOYMENT_ID | jq -r '.readyState')

            echo "Current status: $STATUS"

            if [ "$STATUS" = "READY" ]; then
              echo "✅ Deployment successful for rev-dash!"
              exit 0
            elif [ "$STATUS" = "ERROR" ]; then
              echo "❌ Deployment failed!"
              exit 1
            fi

            sleep 10
          done

          echo "❌ Timeout waiting for deployment"
          exit 1

